#!/usr/bin/env node

/**
 * QA Auto-Fix Script — Sub-Phase 3A
 * Applies AI-generated fixes to QA failures using Git unified diff patches
 *
 * Workflow:
 * 1. Fetch AI analysis comment from the issue
 * 2. Extract file name, line number, code snippets
 * 3. Call Gemini API to generate a unified diff patch
 * 4. Apply the patch using git apply
 * 5. Create a new branch and commit
 * 6. Push branch and create pull request
 * 7. Post confirmation comment on the issue
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ════════════════════════════════════════════════════════════════════════════
// CONFIGURATION & ENVIRONMENT VARIABLES
// ════════════════════════════════════════════════════════════════════════════

const config = {
  issueNumber: process.env.ISSUE_NUMBER,
  issueTitle: process.env.ISSUE_TITLE,
  repoOwner: process.env.REPO_OWNER,
  repoName: process.env.REPO_NAME,
  githubToken: process.env.GITHUB_TOKEN,
  googleApiKey: process.env.GOOGLE_API_KEY,
  commenter: process.env.COMMENTER,
};

const requiredEnvVars = [
  'ISSUE_NUMBER',
  'ISSUE_TITLE',
  'REPO_OWNER',
  'REPO_NAME',
  'GITHUB_TOKEN',
  'GOOGLE_API_KEY',
  'COMMENTER',
];

for (const envVar of requiredEnvVars) {
  if (!process.env[envVar]) {
    console.error(`❌ Missing required environment variable: ${envVar}`);
    process.exit(1);
  }
}

// ════════════════════════════════════════════════════════════════════════════
// STEP 2: FETCH AND PARSE AI ANALYSIS COMMENT
// ════════════════════════════════════════════════════════════════════════════

async function fetchAnalysisComment(issueNumber, repoOwner, repoName, githubToken) {
  const url = `https://api.github.com/repos/${repoOwner}/${repoName}/issues/${issueNumber}/comments`;

  try {
    const response = await fetch(url, {
      headers: {
        'Authorization': `token ${githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
      },
    });

    if (!response.ok) {
      console.error(`GitHub API error (${response.status})`);
      return null;
    }

    const comments = await response.json();

    // Find the AI analysis comment
    const analysisComment = comments.find(comment =>
      comment.body.includes('Root Cause Found') &&
      comment.body.includes('Auto-generated by QA Intelligence Engine')
    );

    return analysisComment ? analysisComment.body : null;
  } catch (err) {
    console.error('Error fetching comments:', err.message);
    return null;
  }
}

// ════════════════════════════════════════════════════════════════════════════
// EXTRACT ANALYSIS DATA FROM MARKDOWN COMMENT
// ════════════════════════════════════════════════════════════════════════════

function parseAnalysisComment(commentBody) {
  if (!commentBody) {
    return null;
  }

  try {
    // Extract File name: between "**File:**" and next line
    const fileMatch = commentBody.match(/\*\*File:\*\*\s*`([^`]+)`/);
    if (!fileMatch) {
      console.error('Could not extract file name from analysis comment');
      return null;
    }
    const fileName = fileMatch[1];

    // Extract Line number: between "**Line:**" and next line
    const lineMatch = commentBody.match(/\*\*Line:\*\*\s*`(\d+)`/);
    if (!lineMatch) {
      console.error('Could not extract line number from analysis comment');
      return null;
    }
    const lineNumber = parseInt(lineMatch[1], 10);

    // Extract short description: between "**Issue:**" and next line
    const descMatch = commentBody.match(/\*\*Issue:\*\*\s*(.+?)(?:\n|$)/);
    if (!descMatch) {
      console.error('Could not extract description from analysis comment');
      return null;
    }
    const shortDescription = descMatch[1].trim();

    // Extract Relevant Code: content in first javascript code block
    const relevantCodeMatch = commentBody.match(/### 📁 Relevant Code\s*```javascript\s*([\s\S]+?)\s*```/);
    if (!relevantCodeMatch) {
      console.error('Could not extract relevant code from analysis comment');
      return null;
    }
    const relevantCode = relevantCodeMatch[1].trim();

    // Extract Suggested Fix: content in second javascript code block
    const suggestedFixMatch = commentBody.match(/### 💡 Suggested Fix\s*```javascript\s*([\s\S]+?)\s*```/);
    if (!suggestedFixMatch) {
      console.error('Could not extract suggested fix from analysis comment');
      return null;
    }
    const suggestedFix = suggestedFixMatch[1].trim();

    return {
      fileName,
      lineNumber,
      shortDescription,
      relevantCode,
      suggestedFix,
    };
  } catch (err) {
    console.error('Error parsing analysis comment:', err.message);
    return null;
  }
}

// ════════════════════════════════════════════════════════════════════════════
// STEP 3: CALL GEMINI API TO GENERATE UNIFIED DIFF PATCH
// ════════════════════════════════════════════════════════════════════════════

async function generateUnifiedDiffPatch(
  fileName,
  relevantCode,
  suggestedFix,
  apiKey
) {
  // Read the actual file content
  let fileContent;
  try {
    fileContent = fs.readFileSync(fileName, 'utf8');
  } catch (err) {
    console.error(`Error reading file ${fileName}:`, err.message);
    return null;
  }

  const prompt = `You are a senior software engineer.
Generate a Git unified diff patch to fix this bug.

File: ${fileName}

Current buggy code:
${relevantCode}

Fixed code:
${suggestedFix}

File content:
${fileContent}

Return ONLY a valid unified diff patch in this exact format,
no markdown, no extra text, no backticks:

--- a/${fileName}
+++ b/${fileName}
@@ -lineNumber,count +lineNumber,count @@
 context line
-buggy line
+fixed line
 context line

Rules for the patch:
- Include 3 lines of context before and after the change
- Use correct line numbers from the actual file content
- Only change the minimum lines necessary
- Patch must apply cleanly with: git apply patch.diff`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt,
              },
            ],
          },
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error(`Gemini API error (${response.status}):`, errorText);
      return null;
    }

    const data = await response.json();

    if (!data.candidates || data.candidates.length === 0) {
      console.error('No candidates in Gemini response');
      return null;
    }

    const content = data.candidates[0].content;
    if (!content || !content.parts || content.parts.length === 0) {
      console.error('No content parts in Gemini response');
      return null;
    }

    return content.parts[0].text;
  } catch (err) {
    console.error('Error calling Gemini API:', err.message);
    return null;
  }
}

// ════════════════════════════════════════════════════════════════════════════
// STEP 4: APPLY GIT UNIFIED DIFF PATCH
// ════════════════════════════════════════════════════════════════════════════

function applyPatch(patchContent) {
  const patchFile = '/tmp/fix.patch';

  try {
    // Write patch to temporary file
    fs.writeFileSync(patchFile, patchContent, 'utf8');
    console.log('✅ Patch file written to /tmp/fix.patch');

    // Try to apply the patch
    console.log('\n📋 Applying patch with: git apply /tmp/fix.patch');
    try {
      execSync('git apply /tmp/fix.patch', { stdio: 'inherit' });
      console.log('✅ Patch applied successfully');
      return true;
    } catch (err) {
      console.warn('⚠️  git apply failed, trying with --ignore-whitespace');
      try {
        execSync('git apply --ignore-whitespace /tmp/fix.patch', { stdio: 'inherit' });
        console.log('✅ Patch applied with --ignore-whitespace');
        return true;
      } catch (err2) {
        console.error('❌ git apply failed even with --ignore-whitespace');
        return false;
      }
    }
  } catch (err) {
    console.error('Error applying patch:', err.message);
    return false;
  }
}

// ════════════════════════════════════════════════════════════════════════════
// STEP 5: CREATE BRANCH AND COMMIT
// ════════════════════════════════════════════════════════════════════════════

function createBranchAndCommit(
  issueNumber,
  fileName,
  issueTitle,
  commenter
) {
  // Extract filename without extension
  const fileNameWithoutExt = path.parse(fileName).name;
  const branchName = `fix/issue-${issueNumber}-${fileNameWithoutExt}`;

  try {
    console.log(`\n🌿 Creating branch: ${branchName}`);
    execSync(`git checkout -b ${branchName}`, { stdio: 'inherit' });

    console.log(`📝 Staging file: ${fileName}`);
    execSync(`git add ${fileName}`, { stdio: 'inherit' });

    const commitMessage = `fix: resolve QA failure from issue #${issueNumber}

Auto-fix applied by QA Intelligence Engine

Issue: ${issueTitle}
File: ${fileName}
Requested by: @${commenter}

Co-authored-by: QA Bot <qa-bot@github-actions>`;

    console.log('💾 Creating commit');
    execSync(`git commit -m "${commitMessage}"`, { stdio: 'inherit' });

    console.log(`📤 Pushing branch to origin/${branchName}`);
    execSync(`git push origin ${branchName}`, { stdio: 'inherit' });

    console.log('✅ Branch created, committed, and pushed');
    return branchName;
  } catch (err) {
    console.error('Error creating branch/commit:', err.message);
    return null;
  }
}

// ════════════════════════════════════════════════════════════════════════════
// STEP 6: CREATE PULL REQUEST VIA GITHUB API
// ════════════════════════════════════════════════════════════════════════════

async function createPullRequest(
  issueNumber,
  fileName,
  branchName,
  repoOwner,
  repoName,
  issueTitle,
  shortDescription,
  commenter,
  githubToken
) {
  const url = `https://api.github.com/repos/${repoOwner}/${repoName}/pulls`;

  const prTitle = `fix: ${issueTitle} (Auto-fix #${issueNumber})`;

  const prBody = `## 🤖 Automated Fix — QA Intelligence Engine

This PR was automatically generated in response to a QA failure.

### 📋 Issue
Closes #${issueNumber}

### 📍 Change
**File:** ${fileName}
**Fix type:** Surgical patch (unified diff)

### 🔍 What Changed
${shortDescription}

### ✅ How to Review
1. Check the diff — only the buggy lines were changed
2. Run the failing test case again to verify the fix
3. Approve and merge if tests pass

---
*Auto-generated by QA Intelligence Engine · Sub-Phase 3A*
*Requested by @${commenter} via /fix implement*`;

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `token ${githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title: prTitle,
        body: prBody,
        head: branchName,
        base: 'main',
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error(`GitHub API error (${response.status}):`, errorText);
      return null;
    }

    const prData = await response.json();
    console.log(`✅ Pull request created: ${prData.html_url}`);
    return prData.html_url;
  } catch (err) {
    console.error('Error creating pull request:', err.message);
    return null;
  }
}

// ════════════════════════════════════════════════════════════════════════════
// STEP 7: POST CONFIRMATION COMMENT ON ISSUE
// ════════════════════════════════════════════════════════════════════════════

async function postConfirmationComment(
  issueNumber,
  branchName,
  fileName,
  prUrl,
  repoOwner,
  repoName,
  commenter,
  githubToken
) {
  const url = `https://api.github.com/repos/${repoOwner}/${repoName}/issues/${issueNumber}/comments`;

  const comment = `## ✅ Fix Applied — Pull Request Created

> Auto-generated by QA Intelligence Engine (Sub-Phase 3A)

---

### 🔀 Pull Request
${prUrl}

### 📍 What Was Done
- Branch created: \`${branchName}\`
- Surgical patch applied to \`${fileName}\`
- Only the buggy lines were changed (unified diff)
- PR is ready for review

### 👀 Next Steps
1. Review the PR diff
2. Run the test case again to verify
3. Merge when satisfied

---
*Requested by @${commenter} · Fix applied using Git unified diff patch*`;

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `token ${githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ body: comment }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error(`GitHub API error (${response.status}):`, errorText);
      return false;
    }

    console.log('✅ Confirmation comment posted on issue');
    return true;
  } catch (err) {
    console.error('Error posting confirmation comment:', err.message);
    return false;
  }
}

// ════════════════════════════════════════════════════════════════════════════
// ERROR HELPER: POST ERROR COMMENT ON ISSUE
// ════════════════════════════════════════════════════════════════════════════

async function postErrorComment(
  issueNumber,
  errorMessage,
  repoOwner,
  repoName,
  githubToken
) {
  const url = `https://api.github.com/repos/${repoOwner}/${repoName}/issues/${issueNumber}/comments`;

  const comment = `## ⚠️ Auto-Fix Failed

> Auto-generated by QA Intelligence Engine (Sub-Phase 3A)

---

${errorMessage}`;

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `token ${githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ body: comment }),
    });

    if (!response.ok) {
      console.error(`GitHub API error (${response.status})`);
      return false;
    }

    console.log('✅ Error comment posted on issue');
    return true;
  } catch (err) {
    console.error('Error posting error comment:', err.message);
    return false;
  }
}

// ════════════════════════════════════════════════════════════════════════════
// MAIN EXECUTION
// ════════════════════════════════════════════════════════════════════════════

async function main() {
  try {
    console.log('════════════════════════════════════════════════════════════════');
    console.log('🤖 QA Auto-Fix Pipeline — Starting');
    console.log('════════════════════════════════════════════════════════════════');

    // Step 2: Fetch and parse analysis comment
    console.log('\n📥 Fetching AI analysis comment from issue #' + config.issueNumber);
    const analysisComment = await fetchAnalysisComment(
      config.issueNumber,
      config.repoOwner,
      config.repoName,
      config.githubToken
    );

    if (!analysisComment) {
      console.error('❌ No AI analysis found on this issue');
      await postErrorComment(
        config.issueNumber,
        'No AI analysis found on this issue.\nPlease wait for the analysis to complete first.',
        config.repoOwner,
        config.repoName,
        config.githubToken
      );
      return;
    }

    console.log('✅ Found AI analysis comment');

    // Parse the analysis
    console.log('\n🔍 Parsing analysis comment');
    const analysis = parseAnalysisComment(analysisComment);

    if (!analysis) {
      console.error('❌ Could not parse analysis comment');
      await postErrorComment(
        config.issueNumber,
        'Failed to parse AI analysis comment. Manual review required.',
        config.repoOwner,
        config.repoName,
        config.githubToken
      );
      return;
    }

    console.log('✅ Extracted analysis data:');
    console.log(`   - File: ${analysis.fileName}`);
    console.log(`   - Line: ${analysis.lineNumber}`);
    console.log(`   - Issue: ${analysis.shortDescription}`);

    // Step 3: Generate unified diff patch
    console.log('\n🧠 Generating unified diff patch from Gemini API');
    const patchContent = await generateUnifiedDiffPatch(
      analysis.fileName,
      analysis.relevantCode,
      analysis.suggestedFix,
      config.googleApiKey
    );

    if (!patchContent) {
      console.error('❌ Failed to generate patch');
      await postErrorComment(
        config.issueNumber,
        'Failed to generate patch from AI. Manual fix required.',
        config.repoOwner,
        config.repoName,
        config.githubToken
      );
      return;
    }

    console.log('✅ Generated patch');

    // Step 4: Apply patch
    console.log('\n📋 Applying patch to file');
    const patchApplied = applyPatch(patchContent);

    if (!patchApplied) {
      console.error('❌ Patch could not be applied');
      await postErrorComment(
        config.issueNumber,
        'Patch could not be applied cleanly.\nManual fix required. The suggested fix is in the analysis comment above.',
        config.repoOwner,
        config.repoName,
        config.githubToken
      );
      return;
    }

    // Step 5: Create branch and commit
    console.log('\n🌿 Creating branch and committing');
    const branchName = createBranchAndCommit(
      config.issueNumber,
      analysis.fileName,
      config.issueTitle,
      config.commenter
    );

    if (!branchName) {
      console.error('❌ Failed to create branch/commit');
      await postErrorComment(
        config.issueNumber,
        'Failed to create branch and commit. Manual fix required.',
        config.repoOwner,
        config.repoName,
        config.githubToken
      );
      return;
    }

    // Step 6: Create pull request
    console.log('\n📬 Creating pull request');
    const prUrl = await createPullRequest(
      config.issueNumber,
      analysis.fileName,
      branchName,
      config.repoOwner,
      config.repoName,
      config.issueTitle,
      analysis.shortDescription,
      config.commenter,
      config.githubToken
    );

    if (!prUrl) {
      console.error('❌ Failed to create pull request');
      await postErrorComment(
        config.issueNumber,
        `Branch ${branchName} already exists.\nA fix may have already been applied.`,
        config.repoOwner,
        config.repoName,
        config.githubToken
      );
      return;
    }

    // Step 7: Post confirmation comment
    console.log('\n💬 Posting confirmation comment');
    await postConfirmationComment(
      config.issueNumber,
      branchName,
      analysis.fileName,
      prUrl,
      config.repoOwner,
      config.repoName,
      config.commenter,
      config.githubToken
    );

    console.log('\n════════════════════════════════════════════════════════════════');
    console.log('✅ Auto-Fix Pipeline Complete');
    console.log('════════════════════════════════════════════════════════════════');
  } catch (err) {
    console.error('\n❌ Unexpected error:', err.message);
    console.error(err.stack);
    process.exit(1);
  }
}

main();
